return {
  "williamboman/mason.nvim",
  dependencies = { "williamboman/mason.nvim" },
  opts = {
    ensure_installed = {
      "ast-grep",
      "angular-language-server",
      "bash-language-server",
      "css-lsp",
      "eslint-lsp",
      "gopls",
      "golangci-lint",
      "goimports",
      "gofumpt",
      "gomodifytags",
      "impl",
      "delve",
      "jdtls",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "prisma-language-server",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "gradle-language-server",
      "python-lsp-server",
    },
  },
}
